### ISSUE TITLE
Microformats2 support

### ISSUE THREAD

**Issue by paulcmal** [edhelas/atomtopubsub#3]
Hey,

Would it be feasible to support [microformats2](http://microformats.org) parsing? This would be a first step into getting [Indieweb](https://indieweb.org)->XMPP communication going.

atom is a quite old standard. mf2 is standard as well but a lot clearer and more customizable.

See [mf2util](https://github.com/kylewm/mf2util).

**Comment by edhelas** [comment]
For the moment I'm only planning to support the Atom format as an input source for atomtopubsub but you're free to propose some PR to add more formats :)
