### ISSUE TITLE
resulting items are not standard XEP-0277, atomtopubsub should not be used until fixed

### ISSUE THREAD

**Issue by goffi-contrib** [edhelas/atomtopubsub#9]
Hello,

In addition to https://github.com/edhelas/atomtopubsub/issues/4 atomtopubsub is escaping XML tags, which is not standard and make it unusable.

Please check https://xmpp.org/extensions/xep-0277.html#rich_content for the correct way to publish items, XML tags of `title` or `content` must not be escaped.

Thanks

**Comment by edhelas** [comment]
Fixed in PR #10
